In [35]:
import sys
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [36]:
# from google.colab import files
# uploaded = files.upload()
# import io

df = pd.read_csv('all_poems.csv')
df.poem_text=df.poem_text.astype(str)


ParserError: Error tokenizing data. C error: out of memory

In [ ]:
df.head()


In [ ]:
df.info()

In [ ]:
df.columns


In [ ]:
df['poet_cat'].describe()


In [ ]:
df['poet_name'].describe()


In [ ]:
df['poem_style'].describe()


In [ ]:
df.tail(10)

In [ ]:
df.shape


In [ ]:
# seeing how many null values
df.isnull().sum()

In [ ]:
df.drop(["poem_style"], axis=1, inplace=True)
df.drop(["poem_link"], axis=1, inplace=True)
df.drop(["poet_link"], axis=1, inplace=True)


In [ ]:
df = df.drop_duplicates()
df.shape

In [ ]:
df['poet_cat'].unique()

In [ ]:
df['poet_cat'].value_counts()

In [ ]:
df['poet_name'].unique()

In [ ]:
df['poet_name'].value_counts()

In [ ]:
import numpy as np


In [ ]:
chart = sns.catplot(
    data=df,
    kind='count',
    x='poet_cat'
)
chart.set_xticklabels(rotation=65, horizontalalignment='right')



In [ ]:
chart = sns.catplot(
    data=df[df['poet_cat'].isin(["العصر العباسي"])],
    kind='count',
    x='poet_name')
chart.set_xticklabels(rotation=65, horizontalalignment='right')


In [ ]:
chart = sns.catplot(
    data=df[df['poet_cat'].isin(["العراق"])],
    kind='count',
    x='poet_name')
chart.set_xticklabels(rotation=65, horizontalalignment='right')


In [ ]:
chart = sns.catplot(
    data=df[df['poet_cat'].isin(["سوريا"])],
    kind='count',
    x='poet_name')
chart.set_xticklabels(rotation=65, horizontalalignment='right')
 

In [ ]:
chart = sns.catplot(
    data=df[df['poet_cat'].isin(["تونس"])],
    kind='count',
    x='poet_name')
chart.set_xticklabels(rotation=65, horizontalalignment='right')
  


In [ ]:
chart = sns.catplot(
    data=df[df['poet_cat'].isin(["العصر العباسي"])],
    kind='count',
    x='poet_name',
    order=pd.value_counts(df['poet_name']).iloc[:20].index)
chart.set_xticklabels(rotation=65, horizontalalignment='right')


In [ ]:
labels ='العراق', 'سوريا', 'مصر', 'تونس', 'السعودية', 'لبنان', 'فلسطين','اليمن', 'العصر الجاهلي', 'العصر الأندلسي', 'السودان', 'البحرين', 'العصر الإسلامي', 'العصر العباسي', 'ليبيا', 'عمان', 'المغرب','الجزائر', 'الإمارات', 'الأردن', 'الكويت', 'قطر', 'موريتانيا','شعراء العراق والشام', 'أفغانستان','إيران'

sizes = [90,70,68,15,22,54,265,563,405,202,619,240,19417,3700,555,403,6296,1461,700,1713,4800,1931,351,4793,5036,4252]


fig1, ax1 = plt.subplots(figsize=(5,5))
ax1.pie(sizes, labels=labels, autopct='%1.1f%%',
        shadow=False, startangle=90)
ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.

plt.show()

In [ ]:
new_data = df.drop(["poet_cat"], axis=1)
new_data = new_data.drop(["poem_id"], axis=1)
new_data = new_data.drop(["poet_id"], axis=1)

dflabel = df[['poet_cat']]

new_data.insert(len(new_data.columns),"poet_cat",dflabel)
new_data

In [ ]:
# Create two pandas arrays -- one for X and one for Y to get ready 
# for neural network

# convert the array into a numpy array
arr = new_data.to_numpy()

# separate X and Y
Y = arr[:,3]

In [ ]:
# X

In [38]:
Y=Y.astype(str)

Y

array(['العراق', 'العراق', 'العراق', ..., 'سوريا', 'سوريا', 'سوريا'],
      dtype='<U19')

In [41]:
X = arr[:,0]
X=X.astype(str)
X

MemoryError: Unable to allocate 14.3 GiB for an array with shape (58021,) and data type <U66350

In [31]:
import argparse

from nltk.stem.isri import ISRIStemmer
import sys


# Arabic light stemming for Arabic text
# takes a word list and perform light stemming for each Arabic words
def light_stem(text):
    words = text.split()
    result = list()
    stemmer = ISRIStemmer()
    for word in words:
        word = stemmer.norm(word, num=1)      # remove diacritics which representing Arabic short vowels
        if not word in stemmer.stop_words:    # exclude stop words from being processed
            word = stemmer.pre32(word)        # remove length three and length two prefixes in this order
            word = stemmer.suf32(word)        # remove length three and length two suffixes in this order
            word = stemmer.waw(word)          # remove connective ‘و’ if it precedes a word beginning with ‘و’
            word = stemmer.norm(word, num=2)  # normalize initial hamza to bare alif
        result.append(word)
    return ' '.join(result)



In [32]:
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

# from cltk.tokenize.word import WordTokenizer
# word_tokenizer = WordTokenizer('arabic')
# word_tokenizer.tokenize()
# vocab_size = len(word_tokenizer.word_index) + 1


# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(X)
vocab_size = len(t.word_index) + 1




Using TensorFlow backend.
C:\Users\Lana\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Lana\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Lana\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Lana\Anaconda3\envs\tf_gpu\lib\site-pa

In [33]:
stemmed=light_stem(t)

TypeError: 'str' object is not callable

In [ ]:

# integer encode the documents
encoded_docs = t.texts_to_sequences(X)
print(encoded_docs)




In [ ]:

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)


In [ ]:
# # load the whole embedding into memory
# embeddings_index = dict()
# f = open('wiki.ar.vec',encoding='utf-8')
# for line in f:
#     values = line.split()
#     word = values[0]
#     coefs = asarray(values[1:],dtype='float32')
#     embeddings_index[word] = coefs
# f.close()

In [ ]:
import io

def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = map(float, tokens[1:])
    return data
data=load_vectors('wiki.ar.vec')

In [51]:
print('Loaded %s word vectors.' % len(embeddings_index))


# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 301))
print(embedding_matrix)
for word, i in t.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector


Loaded 610625 word vectors.
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


ValueError: could not convert string to float: 'كلية'

In [39]:
# define model
model = Sequential()
e = Embedding(vocab_size, 301, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
docs=np.asarray(padded_docs)
print("ho")
print(docs)
print(padded_docs)
print(labels)
labelss=np.asarray(labels)
model.fit(docs, Y, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 4, 300)            8700      
_________________________________________________________________
flatten_9 (Flatten)          (None, 1200)              0         
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 1201      
Total params: 9,901
Trainable params: 1,201
Non-trainable params: 8,700
_________________________________________________________________
None
ho
[[7 0 0 0]
 [7 0 0 0]
 [7 0 0 0]
 ...
 [4 0 0 0]
 [4 0 0 0]
 [4 0 0 0]]
[[7 0 0 0]
 [7 0 0 0]
 [7 0 0 0]
 ...
 [4 0 0 0]
 [4 0 0 0]
 [4 0 0 0]]
('العراق', 'سوريا', 'مصر', 'تونس', 'السعودية', 'لبنان', 'فلسطين', 'اليمن', 'العصر الجاهلي', 'العصر الأندلسي', 'السودان', 'البحرين', 'العصر الإسلامي', 'العصر العباسي', 'ليبيا', 'عمان', 'المغرب', 'الجزائر', 'الإمارات', 'الأردن', 'الكويت', 'قطر', 'مور

ValueError: Input arrays should have the same number of samples as target arrays. Found 58021 input samples and 26 target samples.

In [ ]:
# Prepare Y values for one-hot encoding

from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)


In [ ]:
import re
import string

df.poem_text = df.poem_text.str.replace("ing( |$)", " ")
df.poem_text = df.poem_text.str.replace("[^a-zA-Z]", " ")
df.poem_text = df.poem_text.str.replace("ies( |$)", "y ")

#function to remove punctuation
def removePunctuation(x):
    x = str(x).lower()
    x = re.sub(r'[^\x00-\x7f]',r' ',x)
    x = x.replace('\r','')
    x = x.replace('\n','')
    x = x.replace('  ','')
    x = x.replace('\'','')
    x = x.replace('*','')
    return re.sub("["+string.punctuation+"]", " ", x)

#getting stop words
from nltk.corpus import stopwords
stops = set(stopwords.words("english")) 
#function to remove stopwords
def removeStopwords(x):
    filtered_words = [word for word in x.split() if word not in stops]
    return " ".join(filtered_words)


def processText(x):
    x= removePunctuation(x)
#     x= removeStopwords(x)
    return x


In [ ]:
import nltk
# nltk.download()

from nltk.tokenize import sent_tokenize, word_tokenize
X= pd.Series([word_tokenize(processText(x)) for x in new_data['poem_text']])
X.head()


def sent_to_words(content):
    return [np.array([x.split() for x in poem.split()]) for poem in content]

poem = sent_to_words(new_data.poem_text)

def build_dict(poem):
    dictionary = {}
    rev_dict = {}
    count = 0
    for content in poem:
        for i in content:
            if i[0] in dictionary:
                pass
            else:
                dictionary[i[0]] = count
                count += 1
    rev_dict = dict(zip(dictionary.values(), dictionary.keys()))
    return dictionary, rev_dict
dictionary, rev_dict = build_dict(poem)


In [ ]:
X

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

vocab_size = len(dictionary)


# define the keras model
model = Sequential()
model.add(Dense(5, input_dim=1, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(26, activation = 'softmax'))

In [ ]:
# compile the keras model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X, dummy_y, validation_split=0.25, epochs=50, batch_size=32, verbose=1)

In [ ]:
# Plot training & validation accuracy values
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Training','Validation'], loc='upper left')

plt.show()
